(ns koe.carrier-test
  "The edge: unauthenticated bytes from the public internet.

  The signature test uses Twilio's own **published** example — URL, parameters,
  auth token and expected signature all taken from their validation
  documentation — rather than a value this code produced and then asserted
  against itself. A self-generated vector proves the implementation is
  self-consistent, which is exactly what a wrong implementation also is.

  It earned its place immediately: the first version of this test carried a
  vector written from memory, with the wrong host and the wrong signature, and it
  failed. The implementation was right. Had the vector been generated by the code
  under test, it would have passed and proved nothing."
  (:require [kotoba.lang.text :as str]
            [clojure.test :refer [deftest is testing]]
            [koe.arrival :as arrival]
            [koe.carrier :as carrier]))

;; Twilio's documented example.
(def ^:private doc-url "https://example.com/myapp.php?foo=1&bar=2")
(def ^:private doc-token "12345")
(def ^:private doc-params
  ;; Deliberately NOT in sorted order. The first version of this map listed the
  ;; parameters alphabetically, so a verifier that never sorted still produced
  ;; the documented signature and the known-answer test passed with the sort
  ;; removed (measured). A canonical vector that does not exercise the
  ;; canonicalisation is not testing the thing it appears to test.
  (array-map "To" "+18005551212"
             "From" "+14158675310"
             "Digits" "1234"
             "Caller" "+14158675310"
             "CallSid" "CA1234567890ABCDE"))
(def ^:private doc-signature "L/OH5YylLD5NRKLltdqwSvS0BnU=")

(defn- req [& kvs]
  (merge {:provider :twilio :url doc-url :params doc-params
          :signature doc-signature :secret doc-token}
         (apply hash-map kvs)))

;; ── signature ────────────────────────────────────────────────────────────────

(deftest test-twilios-own-published-vector-verifies
  (is (carrier/verify (req))))

(deftest test-the-signing-string-is-the-documented-one
  (is (= (str doc-url "CallSidCA1234567890ABCDECaller+14158675310Digits1234"
              "From+14158675310To+18005551212")
         (carrier/twilio-signing-string doc-url doc-params))))

(deftest test-reordering-parameters-cannot-change-the-string
  (testing "the sort is the security property, not a tidiness preference"
    (is (= (carrier/twilio-signing-string doc-url doc-params)
           (carrier/twilio-signing-string doc-url (into (sorted-map-by #(compare %2 %1)) doc-params))))))

(deftest test-any-tampering-fails
  (doseq [[label r] [["a changed caller"  (req :params (assoc doc-params "From" "+819099999999"))]
                     ["an added parameter" (req :params (assoc doc-params "Digits" "9999"))]
                     ["a changed url"      (req :url "https://example.com/myapp.php?foo=1&bar=3")]
                     ["a wrong token"      (req :secret "12346")]
                     ["a wrong signature"  (req :signature "AAAAAAAAAAAAAAAAAAAAAAAAAAA=")]]]
    (is (false? (carrier/verify r)) label)))

(deftest test-what-cannot-be-checked-is-not-verified
  (testing "absent inputs return false, never nil — a nil reads as fine at a call site"
    (doseq [[label r] [["no signature" (req :signature nil)]
                       ["empty signature" (req :signature "")]
                       ["no secret"    (req :secret nil)]
                       ["no url"       (req :url "")]
                       ["params absent" (req :params nil)]]]
      (is (false? (carrier/verify r)) label))))

(deftest test-an-unimplemented-provider-is-refused-not-assumed
  (is (false? (carrier/verify (req :provider :telnyx))))
  (is (= :unimplemented-provider (:reason (carrier/admit (req :provider :telnyx)))))
  (testing "and it is refused even with a signature that would satisfy Twilio's scheme"
    (is (not (:admitted (carrier/admit (req :provider :vonage)))))))

;; ── the call as described ────────────────────────────────────────────────────

(defn- inbound [& kvs]
  (merge {"CallSid" "CA-1" "From" "+819012345678" "To" "+815012345678"
          "Direction" "inbound"}
         (apply hash-map kvs)))

(deftest test-a-direct-call-yields-the-callers-number
  (let [a (carrier/arrival :twilio (inbound))]
    (is (= :direct (:via a)))
    (is (= :network-caller (:provenance a)))
    (is (= "+819012345678" (:koe/contact (arrival/caller-contact a))))))

(deftest test-a-forwarded-call-does-not-claim-to-know-the-caller
  (testing "nothing in the webhook distinguishes 'passed through' from 'replaced'"
    (let [a (carrier/arrival :twilio (inbound "ForwardedFrom" "+815099998888"))]
      (is (= :forwarded (:via a)))
      (is (= :diverted-unknown (:provenance a)))
      (testing "so the number is not used, and the caller is asked"
        (is (nil? (:koe/contact (arrival/caller-contact a))))))))

(deftest test-a-diversion-presenting-the-shop-line-is-caught-twice
  (let [a (carrier/arrival :twilio (inbound "From" "+815099998888"
                                            "ForwardedFrom" "+815099998888"))]
    (is (= :diverted-unknown (:provenance a)))
    (is (nil? (:koe/contact (arrival/caller-contact a))))))

;; ── what we answer with ──────────────────────────────────────────────────────

(deftest test-the-answer-connects-the-call-rather-than-tapping-it
  (let [xml (carrier/answer-document {:stream-url "wss://denwaban.example/media"})]
    (is (str/includes? xml "<Connect>"))
    (is (not (str/includes? xml "<Start>"))
        "Start forks a copy and leaves the call up: that is a listening device")))

(deftest test-an-insecure-stream-url-is-refused
  (doseq [u ["ws://denwaban.example/media" "https://denwaban.example/media" ""]]
    (is (thrown? #?(:clj Exception :cljs js/Error)
                 (carrier/answer-document {:stream-url u})))))

(deftest test-a-greeting-is-escaped
  (let [xml (carrier/answer-document {:stream-url "wss://x/y" :greeting "<b>&\""})]
    (is (str/includes? xml "&lt;b&gt;&amp;&quot;"))
    (is (not (str/includes? xml "<b>")))))

(deftest test-an-unverified-request-is-answered-with-a-hangup-and-nothing-else
  (is (str/includes? carrier/refusal-document "<Hangup/>"))
  (testing "no spoken message: the party at the other end is unknown"
    (is (not (str/includes? carrier/refusal-document "<Say")))))

(deftest test-admit-is-the-boundary
  (is (:admitted (carrier/admit (req))))
  (is (= :signature-not-verified (:reason (carrier/admit (req :signature "bad")))))
  (testing "an admitted request hands on the arrival, not the raw parameters"
    (is (contains? (carrier/admit (req)) :arrival))))
